@echo off
echo Fixing dependencies...
cd /d "c:\Users\hp\Downloads\AI-MARKET-MAIN\silly-ocelot-burst-main"
echo Deleting old lockfiles...
del pnpm-lock.yaml
del package-lock.json
echo Installing with npm...
npm install
echo Committing changes...
git add package-lock.json vercel.json
git commit -m "Fix: Switch to npm and regenerate lockfile"
echo Pushing to GitHub...
git push origin main
echo Done! Now redeploy on Vercel dashboard.