@echo off
echo Removing secrets from git...
cd /d "c:\Users\hp\Downloads\AI-MARKET-MAIN"
echo Removing .env from tracking...
git rm --cached silly-ocelot-burst-main/.env
git rm --cached backend/.env
echo Amending commits to remove secrets...
git commit --amend --no-edit
echo Force pushing to remove secrets from repository...
git push -u origin main --force
echo Done! Secrets removed and repository cleaned.